name: Build & Verify Solution

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Rebuild Solution
      run: msbuild Typhon.sln /t:Rebuild /p:Configuration=Release /p:Platform="x86"
